name: Practical Lab exercise Week 3  - CI Pipeline - 
on: [push]

jobs:
  build-and-test:
    name: Build and Test Project on Node.js 20.12.1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20.12.1
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
