name: Docker image test-facing build and push

on:
  push:        # triggers the workflow every time you push code
    branches:
      - main   # or 'master' — use your default branch name
   
   
jobs:
  build-and-deploy:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Set up Docker Buildx (build tool)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Build and push image to Docker Hub
      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfiles/test.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iat-inventory:test-latest
